former_gpio_node:
  ros__parameters:
    port: "/dev/gpio"
    baud: 115200
    ultrasonic_frame: ["left_ultrasonic", "right_ultrasonic"]
    convert_range_to_scan: false
    digital_io_topic: ["docked"]


controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    former_base_controller:
      type: diff_drive_controller/DiffDriveController


former_base_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    publish_rate: 50.0
    pose_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    wheel_separation: 0.4 #0.305
    #wheels_per_side: 1  # actually 2, but both are controlled by 1 signal
    wheel_radius: 0.085

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.1
    right_wheel_radius_multiplier: 1.1


    odom_frame_id: odom
    base_frame_id: base_link
    
    open_loop: false
    enable_odom_tf: true

    cmd_vel_timeout: 0.25
    use_stamped_vel: false
    preserve_turning_radius: true

    publish_cmd: true
    publish_wheel_data: true

    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 1.5
    linear.x.min_velocity: -1.5
    linear.x.max_acceleration: 2.0
    linear.x.min_acceleration: -2.0
    linear.x.max_jerk: 0.0
    linear.x.min_jerk: 0.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 3.0
    angular.z.min_velocity: -3.0
    angular.z.max_acceleration: 3.0
    angular.z.min_acceleration: -3.0
    angular.z.max_jerk: 0.0
    angular.z.min_jerk: 0.0


ekf_node:
  ros__parameters:
    frequency: 50
    sensor_timeout: 0.1

    two_d_mode: true
    publish_tf: true
    publish_acceleration: false
    print_diagnostics: false
    debug: false

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    odom0: /former_base_controller/odom
    odom0_config: [true, true, false,
                  false, false, true,
                  true, false, false,
                  false, false, true,
                  false, false, false]
    odom0_differential: false
    odom0_relative: false

    imu0: /imu/data
    imu0_config: [false, false, false,
                  false, false, false,
                  false, false, false,
                  false, false, true,
                  true, false, false]
    imu0_differential: false
    imu0_relative: false
    imu0_remove_gravitational_acceleration: true


twist_mux:
  ros__parameters:
    topics:
      joystick:
        topic   : teleop/cmd_vel
        timeout : 0.5
        priority: 100
      navigation:
        topic   : navigation/cmd_vel
        timeout : 0.5
        priority: 50
      docking:
        topic   : dock/cmd_vel
        timeout : 0.5
        priority: 20
      external:
        topic   : cmd_vel
        timeout : 0.5
        priority: 10

    locks:
      emergency_stop:
        topic   : emergency_stop
        timeout : 0.0
        priority: 255
