uint8 GOAL_TYPE_RECOVERY=0
uint8 GOAL_TYPE_AVOIDANCE=1
uint8 GOAL_TYPE_LINE_UP=2
uint8 GOAL_TYPE_NORMAL=3

string robot_id
string place_id
string poi_group_id
string poi_id
string wp_id
Location goal
uint8 point_type
uint8 goal_type
---

uint8 SUCCESS=0
uint8 FAILURE=1
uint8 response_code
bool success